"""F3 boundary guard: the Python HTML remediation sink (report/html_report.py:~731,
`{remediation_html}` rendered raw) is DEV-ONLY dead code. Production `openant report
-f html` defers to the Go CLI, which sanitizes remediation HTML through a bluemonday
strict allowlist (apps/vulnfounder-cli/internal/report/types.go SafeRemediation).

There is therefore NO live XSS to fix in Python. What KEEPS it safe is that the
production path never reaches the raw Python sink. These guards fail if someone
re-wires `openant report -f html` back to the Python renderer (which would silently
reopen the sanitizer gap). Guard the boundary; do not sanitize dead code.
"""
import inspect

from openant import cli


def test_cmd_report_html_returns_error_and_does_not_render_in_python():
    src = inspect.getsource(cli.cmd_report)
    # the html branch must short-circuit to the Go-CLI error, not render locally
    assert 'HTML reports are generated by the Go CLI' in src
    # and it must NOT call the raw Python HTML renderer
    assert 'generate_html_report' not in src


def test_cli_does_not_import_the_raw_html_renderer():
    # cli.py must not import generate_html_report at all — if this fails, someone
    # wired the dead sink into a live command.
    cli_src = inspect.getsource(cli)
    assert 'generate_html_report' not in cli_src


def test_python_html_sink_is_marked_dev_only():
    # The raw sink carries a DEV-ONLY marker so a future maintainer knows the live
    # (Go) path is the sanitized one and does not "helpfully" re-enable this renderer.
    from report import html_report
    doc = inspect.getsource(html_report.generate_html_report)
    assert 'DEV-ONLY' in doc or 'dev-only' in doc
