package server

// Web-facing orchestration for the Claude Code dynamic-test mode. The task
// workspace is generated by the Python pipeline, while this file owns the
// browser protocol: task preparation, PTY conversation events, and a strictly
// read-only workspace browser.

import (
	"bytes"
	"crypto/subtle"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/knostic/open-ant-cli/internal/python"
	"github.com/knostic/open-ant-cli/internal/types"
)

const (
	maxClaudeMessageBytes = 32 << 10
	maxClaudeTreeEntries  = 4000
	maxClaudeFileBytes    = 4 << 20
)

// prepareAndRunClaudeCode pauses the normal Web pipeline at the dynamic-test
// boundary. The Python command only creates the auditable task package; the
// PTY session then remains interactive until Claude exits or the user presses
// Stop. Report generation happens in runJob after this method returns.
func (s *Server) prepareAndRunClaudeCode(job *Job, outDir, localPath string) error {
	pipelinePath := filepath.Join(outDir, "pipeline_output.json")
	args := []string{
		"dynamic-test", pipelinePath,
		"--output", outDir,
		"--mode", "claude-code",
		"--repo-path", localPath,
	}
	stdout, exitCode, err := python.InvokeCtxCapture(
		job.ctx, s.pythonPath, args, "", "", job.addLog,
	)
	if err != nil {
		return fmt.Errorf("prepare Claude Code task: %w", err)
	}
	if job.ctx.Err() != nil {
		return job.ctx.Err()
	}
	if exitCode >= 2 || exitCode < 0 {
		if messages := envelopeErrors(stdout); len(messages) > 0 {
			return errors.New(strings.Join(messages, "; "))
		}
		return fmt.Errorf("dynamic-test task preparation exited with code %d", exitCode)
	}

	var envelope types.Envelope
	if err := unmarshalLastEnvelope(stdout, &envelope); err != nil {
		return fmt.Errorf("parse dynamic-test task response: %w", err)
	}
	if envelope.Status != "success" {
		if len(envelope.Errors) > 0 {
			return errors.New(strings.Join(envelope.Errors, "; "))
		}
		return fmt.Errorf("dynamic-test task preparation returned status %q", envelope.Status)
	}
	data, err := json.Marshal(envelope.Data)
	if err != nil {
		return fmt.Errorf("marshal dynamic-test task response: %w", err)
	}
	var result types.DynamicTestData
	if err := json.Unmarshal(data, &result); err != nil {
		return fmt.Errorf("decode dynamic-test task response: %w", err)
	}
	if result.Mode != "claude-code" || strings.TrimSpace(result.TaskWorkspace) == "" {
		return fmt.Errorf("dynamic-test response did not contain a Claude Code task workspace")
	}

	info := &claudeTaskInfo{
		Mode:              result.Mode,
		TaskWorkspace:     result.TaskWorkspace,
		PublicToolLibrary: result.PublicToolLibrary,
		TaskManifestPath:  result.TaskManifestPath,
		CandidateManifest: result.CandidateManifest,
		LaunchCommand:     result.LaunchCommand,
		CandidateCount:    result.FindingsTested,
	}
	if _, _, err := s.validateClaudeTaskRoot(job, info); err != nil {
		return fmt.Errorf("reject Claude Code task workspace: %w", err)
	}

	// A successful preparation with no dynamically-testable findings is a
	// normal terminal condition, not a failed scan. Keep the generated task
	// metadata available for audit/browsing, but do not launch an empty Claude
	// Code session or wait for operator input that can never produce a verdict.
	if result.FindingsTested <= 0 {
		job.mu.Lock()
		job.claudeTask = info
		job.mu.Unlock()
		if err := s.persistClaudeMeta(job, info); err != nil {
			job.addLog("[dynamic-test] Warning: could not persist empty task metadata: " + err.Error())
		}
		job.addLog("[dynamic-test] No dynamically testable candidates; skipping Claude Code session.")
		return nil
	}

	session := newClaudeSession(info.TaskWorkspace)
	job.mu.Lock()
	job.claudeTask = info
	job.claude = session
	job.mu.Unlock()
	if err := s.persistClaudeMeta(job, info); err != nil {
		job.addLog("[dynamic-test] Warning: could not persist task metadata: " + err.Error())
	}

	// A missing Claude executable is a user-actionable blocked state, not a
	// failed static scan. The session closes its done channel on this path, so
	// runJob can still finish the report and the browser can explain the block.
	if err := session.start(job.ctx, job.addLog); err != nil {
		job.addLog("[dynamic-test] Claude Code is blocked: " + err.Error())
		return nil
	}
	session.wait()
	s.collectClaudeResults(job, outDir, info)
	return nil
}

var allowedClaudeVerdicts = map[string]bool{
	"CONFIRMED": true, "NOT_REPRODUCED": true, "BLOCKED": true,
	"INCONCLUSIVE": true, "ERROR": true, "REQUIRES_PROTOCOL_REVIEW": true,
}

// collectClaudeResults turns the agent-owned results directory into the same
// stable artifacts used by Docker mode. It only accepts regular JSON files
// beneath the generated task root and never treats a malformed verdict as a
// confirmed finding.
func (s *Server) collectClaudeResults(job *Job, outDir string, info *claudeTaskInfo) {
	taskRoot, _, err := s.validateClaudeTaskRoot(job, info)
	if err != nil {
		return
	}
	resultsRoot := filepath.Join(taskRoot, "results")
	verdicts := make([]map[string]any, 0)
	entries, err := os.ReadDir(resultsRoot)
	if err == nil {
		for _, entry := range entries {
			if !entry.IsDir() || entry.Type()&os.ModeSymlink != 0 {
				continue
			}
			verdictPath := filepath.Join(resultsRoot, entry.Name(), "verdict.json")
			f, fi, openErr := openRegularInRoot(taskRoot, verdictPath)
			if openErr != nil || fi.Size() > maxClaudeFileBytes {
				if f != nil {
					_ = f.Close()
				}
				continue
			}
			var verdict map[string]any
			decodeErr := json.NewDecoder(f).Decode(&verdict)
			_ = f.Close()
			if decodeErr != nil || verdict == nil {
				continue
			}
			status, _ := verdict["status"].(string)
			candidateID, _ := verdict["candidate_id"].(string)
			if candidateID == "" || !allowedClaudeVerdicts[status] {
				continue
			}
			verdicts = append(verdicts, verdict)
		}
	}
	sort.Slice(verdicts, func(i, j int) bool {
		left, _ := verdicts[i]["candidate_id"].(string)
		right, _ := verdicts[j]["candidate_id"].(string)
		return left < right
	})

	var summary any
	summaryPath := filepath.Join(resultsRoot, "summary.json")
	if f, fi, openErr := openRegularInRoot(taskRoot, summaryPath); openErr == nil && fi.Size() <= maxClaudeFileBytes {
		_ = json.NewDecoder(f).Decode(&summary)
		_ = f.Close()
	}
	if summary == nil && len(verdicts) == 0 {
		return
	}
	results := make([]map[string]any, 0, len(verdicts))
	for _, verdict := range verdicts {
		candidateID, _ := verdict["candidate_id"].(string)
		status, _ := verdict["status"].(string)
		details, _ := verdict["notes"].(string)
		if strings.TrimSpace(details) == "" {
			detailBytes, marshalErr := json.Marshal(verdict)
			if marshalErr == nil {
				details = string(detailBytes)
			}
		}
		results = append(results, map[string]any{
			"finding_id": candidateID,
			"status":     status,
			"details":    details,
			"evidence":   verdict["causal_evidence"],
		})
	}
	payload := map[string]any{
		"schema_version": "openant.claude-code.dynamic-results.v1",
		"mode":           "claude-code",
		"task_workspace": info.TaskWorkspace,
		"summary":        summary,
		// ``results`` is the compatibility shape consumed by report-data;
		// ``verdicts`` retains the complete Claude audit objects.
		"results":  results,
		"verdicts": verdicts,
	}
	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return
	}
	jsonPath := filepath.Join(outDir, "dynamic_test_results.json")
	if err := os.WriteFile(jsonPath, append(data, '\n'), 0640); err != nil {
		job.addLog("[dynamic-test] Warning: could not collect Claude results: " + err.Error())
		return
	}
	var markdown strings.Builder
	markdown.WriteString("# Claude Code 动态测试结果\n\n")
	markdown.WriteString("- 任务目录：`" + info.TaskWorkspace + "`\n")
	markdown.WriteString("- 候选结论数：" + strconv.Itoa(len(verdicts)) + "\n\n")
	markdown.WriteString("## 候选结论\n\n")
	if len(verdicts) == 0 {
		markdown.WriteString("Claude Code 尚未写入可接受格式的候选结论。\n")
	} else {
		for _, verdict := range verdicts {
			candidateID, _ := verdict["candidate_id"].(string)
			status, _ := verdict["status"].(string)
			markdown.WriteString("- `" + candidateID + "`：**" + status + "**\n")
		}
	}
	mdPath := filepath.Join(outDir, "dynamic_test_results.md")
	if err := os.WriteFile(mdPath, []byte(markdown.String()), 0640); err != nil {
		job.addLog("[dynamic-test] Warning: could not write Claude result summary: " + err.Error())
	}
	patchClaudeReport(outDir, jsonPath, mdPath, verdicts)
	patchClaudePipelineOutput(filepath.Join(outDir, "pipeline_output.json"), verdicts, job.addLog)
	job.addLog(fmt.Sprintf("[dynamic-test] Collected %d Claude Code verdict(s).", len(verdicts)))
}

func patchClaudeReport(outDir, jsonPath, mdPath string, verdicts []map[string]any) {
	path := filepath.Join(outDir, "dynamic-test.report.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	var report map[string]any
	if json.Unmarshal(data, &report) != nil {
		return
	}
	outputs, _ := report["outputs"].(map[string]any)
	if outputs == nil {
		outputs = make(map[string]any)
		report["outputs"] = outputs
	}
	outputs["results_json_path"] = jsonPath
	outputs["results_md_path"] = mdPath
	summary, _ := report["summary"].(map[string]any)
	if summary == nil {
		summary = make(map[string]any)
		report["summary"] = summary
	}
	summary["findings_tested"] = len(verdicts)
	counts := make(map[string]int)
	for _, verdict := range verdicts {
		if status, ok := verdict["status"].(string); ok {
			counts[status]++
		}
	}
	summary["statuses"] = counts
	patched, err := json.MarshalIndent(report, "", "  ")
	if err == nil {
		_ = os.WriteFile(path, append(patched, '\n'), 0640)
	}
}

func patchClaudePipelineOutput(path string, verdicts []map[string]any, onLog func(string)) {
	if len(verdicts) == 0 {
		return
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	var pipeline map[string]any
	if decoder.Decode(&pipeline) != nil {
		return
	}
	byID := make(map[string]map[string]any, len(verdicts))
	for _, verdict := range verdicts {
		id, _ := verdict["candidate_id"].(string)
		if id != "" {
			byID[id] = verdict
		}
	}
	findings, _ := pipeline["findings"].([]any)
	updated := 0
	for _, raw := range findings {
		finding, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		id, _ := finding["id"].(string)
		verdict, ok := byID[id]
		if !ok {
			continue
		}
		status, _ := verdict["status"].(string)
		finding["dynamic_test_status"] = status
		finding["dynamic_test_details"] = verdict
		updated++
	}
	if updated == 0 {
		return
	}
	patched, err := json.MarshalIndent(pipeline, "", "  ")
	if err != nil {
		return
	}
	if err := os.WriteFile(path, append(patched, '\n'), 0640); err != nil {
		if onLog != nil {
			onLog("[dynamic-test] Warning: could not attach Claude verdicts to pipeline output: " + err.Error())
		}
	}
}

func unmarshalLastEnvelope(stdout string, dst *types.Envelope) error {
	// Python's _output_json intentionally emits indented, human-readable JSON.
	// Decode the complete response first so a multi-line envelope is accepted.
	// The line-by-line fallback below preserves compatibility with older
	// commands that emitted a compact envelope alongside diagnostic noise.
	if raw := strings.TrimSpace(stdout); raw != "" {
		var envelope types.Envelope
		if err := json.Unmarshal([]byte(raw), &envelope); err == nil && strings.TrimSpace(envelope.Status) != "" {
			*dst = envelope
			return nil
		}
	}
	lines := strings.Split(stdout, "\n")
	for i := len(lines) - 1; i >= 0; i-- {
		line := strings.TrimSpace(lines[i])
		if line == "" || !strings.HasPrefix(line, "{") {
			continue
		}
		var envelope types.Envelope
		if err := json.Unmarshal([]byte(line), &envelope); err == nil && strings.TrimSpace(envelope.Status) != "" {
			*dst = envelope
			return nil
		}
	}
	return fmt.Errorf("no JSON envelope in command output")
}

func (s *Server) persistClaudeMeta(job *Job, info *claudeTaskInfo) error {
	job.mu.Lock()
	meta := jobMeta{
		ID:                job.ID,
		Repo:              job.Repo,
		StartedAt:         job.StartedAt,
		Platform:          job.platform,
		DynamicTest:       job.dynamicTest,
		DynamicTestMode:   job.dynamicTestMode,
		TaskWorkspace:     info.TaskWorkspace,
		PublicToolLibrary: info.PublicToolLibrary,
		TaskManifestPath:  info.TaskManifestPath,
		CandidateManifest: info.CandidateManifest,
		LaunchCommand:     info.LaunchCommand,
		CandidateCount:    info.CandidateCount,
	}
	job.mu.Unlock()
	data, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(s.outDir, job.ID, "meta.json"), data, 0640)
}

type claudeInfoResponse struct {
	Enabled           bool          `json:"enabled"`
	Mode              string        `json:"mode,omitempty"`
	JobStatus         string        `json:"job_status,omitempty"`
	Status            string        `json:"status"`
	ExitCode          int           `json:"exit_code,omitempty"`
	TaskWorkspace     string        `json:"task_workspace,omitempty"`
	PublicToolLibrary string        `json:"public_tool_library,omitempty"`
	TaskManifestPath  string        `json:"task_manifest_path,omitempty"`
	CandidateManifest string        `json:"candidate_manifest,omitempty"`
	LaunchCommand     string        `json:"launch_command,omitempty"`
	CandidateCount    int           `json:"candidate_count,omitempty"`
	CanInteract       bool          `json:"can_interact"`
	Events            []claudeEvent `json:"events,omitempty"`
}

func (s *Server) claudeInfo(job *Job) claudeInfoResponse {
	job.mu.Lock()
	mode := job.dynamicTestMode
	jobStatus := job.Status
	info := claudeTaskInfo{}
	if job.claudeTask != nil {
		info = *job.claudeTask
	}
	session := job.claude
	job.mu.Unlock()
	response := claudeInfoResponse{
		Enabled:   job.dynamicTest && mode == "claude-code",
		Mode:      mode,
		JobStatus: jobStatus,
		Status:    "preparing",
	}
	if !response.Enabled {
		response.Status = "not_enabled"
		return response
	}
	response.TaskWorkspace = info.TaskWorkspace
	response.PublicToolLibrary = info.PublicToolLibrary
	response.TaskManifestPath = info.TaskManifestPath
	response.CandidateManifest = info.CandidateManifest
	response.LaunchCommand = info.LaunchCommand
	response.CandidateCount = info.CandidateCount
	if session == nil {
		if jobStatus != StatusRunning {
			response.Status = jobStatus
		}
		return response
	}
	status, exitCode, events := session.snapshot()
	response.Status = status
	response.ExitCode = exitCode
	response.CanInteract = status == claudeStatusRunning
	// The info endpoint is also useful when a page is opened after the PTY
	// already emitted its first lines. SSE remains the authoritative stream.
	if len(events) > 20 {
		response.Events = events[len(events)-20:]
	} else {
		response.Events = events
	}
	return response
}

func (s *Server) handleClaudeInfo(w http.ResponseWriter, r *http.Request) {
	job, ok := s.mgr.get(r.PathValue("id"))
	if !ok {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	_ = json.NewEncoder(w).Encode(s.claudeInfo(job))
}

func (s *Server) handleClaudeEvents(w http.ResponseWriter, r *http.Request) {
	job, ok := s.mgr.get(r.PathValue("id"))
	if !ok {
		http.NotFound(w, r)
		return
	}
	flusher, canFlush := w.(http.Flusher)
	w.Header().Set("Content-Type", "text/event-stream; charset=utf-8")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no")

	lastID := int64(-1)
	if raw := strings.TrimSpace(r.Header.Get("Last-Event-ID")); raw != "" {
		if parsed, err := strconv.ParseInt(raw, 10, 64); err == nil {
			lastID = parsed
		}
	}

	// The static scan may still be preparing the task. Wait briefly on the same
	// endpoint rather than making the browser guess when to reconnect.
	var session *claudeSession
	for session == nil {
		job.mu.Lock()
		session = job.claude
		jobStatus := job.Status
		enabled := job.dynamicTest && job.dynamicTestMode == "claude-code"
		job.mu.Unlock()
		if session != nil {
			break
		}
		if !enabled || jobStatus != StatusRunning {
			writeSSEDone(w, jobStatus)
			if canFlush {
				flusher.Flush()
			}
			return
		}
		select {
		case <-r.Context().Done():
			return
		case <-time.After(150 * time.Millisecond):
		}
	}

	initialEvents := session.eventsAfter(lastID)
	writeClaudeEvents(w, initialEvents)
	if len(initialEvents) > 0 {
		lastID = initialEvents[len(initialEvents)-1].ID
	}
	if canFlush {
		flusher.Flush()
	}
	ticker := time.NewTicker(150 * time.Millisecond)
	defer ticker.Stop()
	for {
		select {
		case <-r.Context().Done():
			return
		case <-ticker.C:
		}
		events := session.eventsAfter(lastID)
		if len(events) > 0 {
			writeClaudeEvents(w, events)
			lastID = events[len(events)-1].ID
		}
		status, _, _ := session.snapshot()
		if status == claudeStatusDone || status == claudeStatusStopped ||
			status == claudeStatusBlocked || status == claudeStatusError {
			fmt.Fprintf(w, "event: done\ndata: %s\n\n", status)
			if canFlush {
				flusher.Flush()
			}
			return
		}
		if canFlush {
			flusher.Flush()
		}
	}
}

func writeClaudeEvents(w io.Writer, events []claudeEvent) {
	for _, event := range events {
		data, err := json.Marshal(event)
		if err != nil {
			continue
		}
		fmt.Fprintf(w, "id: %d\ndata: %s\n\n", event.ID, data)
	}
}

func writeSSEDone(w io.Writer, status string) {
	if status == "" {
		status = StatusError
	}
	fmt.Fprintf(w, "event: done\ndata: %s\n\n", status)
}

type claudeMessageRequest struct {
	Message string `json:"message"`
}

func (s *Server) handleClaudeMessage(w http.ResponseWriter, r *http.Request) {
	if !sameOriginOK(r) || !s.validCSRFHeader(r) {
		http.Error(w, "cross-origin request refused", http.StatusForbidden)
		return
	}
	job, ok := s.mgr.get(r.PathValue("id"))
	if !ok {
		http.NotFound(w, r)
		return
	}
	body, err := io.ReadAll(io.LimitReader(r.Body, maxClaudeMessageBytes+1))
	if err != nil || len(body) > maxClaudeMessageBytes {
		http.Error(w, "message is too large", http.StatusRequestEntityTooLarge)
		return
	}
	var request claudeMessageRequest
	if err := json.Unmarshal(body, &request); err != nil {
		http.Error(w, "invalid JSON message", http.StatusBadRequest)
		return
	}
	job.mu.Lock()
	session := job.claude
	job.mu.Unlock()
	if session == nil {
		http.Error(w, "Claude Code session is not ready", http.StatusConflict)
		return
	}
	if err := session.writeMessage(request.Message); err != nil {
		http.Error(w, err.Error(), http.StatusConflict)
		return
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	_ = json.NewEncoder(w).Encode(map[string]any{"ok": true})
}

func (s *Server) handleClaudeStop(w http.ResponseWriter, r *http.Request) {
	if !sameOriginOK(r) || !s.validCSRFHeader(r) {
		http.Error(w, "cross-origin request refused", http.StatusForbidden)
		return
	}
	job, ok := s.mgr.get(r.PathValue("id"))
	if !ok {
		http.NotFound(w, r)
		return
	}
	job.mu.Lock()
	session := job.claude
	job.mu.Unlock()
	if session == nil {
		http.Error(w, "Claude Code session is not ready", http.StatusConflict)
		return
	}
	session.stop()
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	_ = json.NewEncoder(w).Encode(map[string]any{"ok": true})
}

func (s *Server) validCSRFHeader(r *http.Request) bool {
	return subtle.ConstantTimeCompare([]byte(r.Header.Get("X-CSRF-Token")), []byte(s.csrfToken)) == 1
}

type claudeFileEntry struct {
	Path       string    `json:"path"`
	Name       string    `json:"name"`
	Kind       string    `json:"kind"`
	Size       int64     `json:"size,omitempty"`
	ModifiedAt time.Time `json:"modified_at,omitempty"`
	Readable   bool      `json:"readable"`
}

type claudeFilesResponse struct {
	TaskWorkspace string            `json:"task_workspace"`
	Entries       []claudeFileEntry `json:"entries"`
	Truncated     bool              `json:"truncated"`
}

func (s *Server) validateClaudeTaskRoot(job *Job, info *claudeTaskInfo) (string, os.FileInfo, error) {
	if info == nil || info.Mode != "claude-code" || strings.TrimSpace(info.TaskWorkspace) == "" {
		return "", nil, fmt.Errorf("task workspace is unavailable")
	}
	jobRoot := filepath.Join(s.outDir, job.ID)
	taskRoot, err := filepath.Abs(info.TaskWorkspace)
	if err != nil {
		return "", nil, err
	}
	if !withinRoot(jobRoot, taskRoot) {
		return "", nil, fmt.Errorf("task workspace is outside the scan job")
	}
	fi, err := os.Lstat(taskRoot)
	if err != nil || !fi.IsDir() || fi.Mode()&os.ModeSymlink != 0 {
		return "", nil, fmt.Errorf("task workspace is not a regular directory")
	}
	return taskRoot, fi, nil
}

func (s *Server) claudeTaskForJob(job *Job) (*claudeTaskInfo, string, error) {
	job.mu.Lock()
	if job.claudeTask == nil {
		job.mu.Unlock()
		return nil, "", fmt.Errorf("task workspace is not ready")
	}
	copyInfo := *job.claudeTask
	job.mu.Unlock()
	root, _, err := s.validateClaudeTaskRoot(job, &copyInfo)
	if err != nil {
		return nil, "", err
	}
	return &copyInfo, root, nil
}

func safeClaudeRelative(root, raw string) (string, string, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" || filepath.IsAbs(raw) {
		return "", "", fmt.Errorf("invalid file path")
	}
	clean := filepath.Clean(filepath.FromSlash(raw))
	if clean == "." || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return "", "", fmt.Errorf("file path escapes task workspace")
	}
	path := filepath.Join(root, clean)
	if !withinRoot(root, path) {
		return "", "", fmt.Errorf("file path escapes task workspace")
	}
	return filepath.ToSlash(clean), path, nil
}

func (s *Server) handleClaudeFiles(w http.ResponseWriter, r *http.Request) {
	job, ok := s.mgr.get(r.PathValue("id"))
	if !ok {
		http.NotFound(w, r)
		return
	}
	info, root, err := s.claudeTaskForJob(job)
	if err != nil {
		http.Error(w, err.Error(), http.StatusConflict)
		return
	}
	response := claudeFilesResponse{TaskWorkspace: info.TaskWorkspace}
	walkErr := filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == root {
			return nil
		}
		if len(response.Entries) >= maxClaudeTreeEntries {
			response.Truncated = true
			return filepath.SkipDir
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		item := claudeFileEntry{
			Path: filepath.ToSlash(rel),
			Name: entry.Name(),
			Kind: "file",
		}
		if entry.IsDir() {
			item.Kind = "directory"
		} else if entry.Type()&os.ModeSymlink != 0 {
			item.Kind = "symlink"
		} else if !entry.Type().IsRegular() {
			item.Kind = "special"
		}
		if item.Kind == "file" {
			if fi, statErr := entry.Info(); statErr == nil {
				item.Size = fi.Size()
				item.ModifiedAt = fi.ModTime().UTC()
				item.Readable = fi.Mode().IsRegular() && withinRoot(root, path)
			}
		} else if item.Kind == "directory" {
			item.Readable = true
		}
		response.Entries = append(response.Entries, item)
		return nil
	})
	if walkErr != nil && !errors.Is(walkErr, filepath.SkipDir) {
		http.Error(w, "could not enumerate task workspace", http.StatusInternalServerError)
		return
	}
	sort.Slice(response.Entries, func(i, j int) bool {
		return response.Entries[i].Path < response.Entries[j].Path
	})
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	_ = json.NewEncoder(w).Encode(response)
}

type claudeFileResponse struct {
	Path        string `json:"path"`
	Name        string `json:"name"`
	Size        int64  `json:"size"`
	ModifiedAt  string `json:"modified_at"`
	Binary      bool   `json:"binary"`
	Truncated   bool   `json:"truncated"`
	Content     string `json:"content,omitempty"`
	Unavailable string `json:"unavailable,omitempty"`
}

func (s *Server) handleClaudeFile(w http.ResponseWriter, r *http.Request) {
	job, ok := s.mgr.get(r.PathValue("id"))
	if !ok {
		http.NotFound(w, r)
		return
	}
	_, root, err := s.claudeTaskForJob(job)
	if err != nil {
		http.Error(w, err.Error(), http.StatusConflict)
		return
	}
	rel, path, err := safeClaudeRelative(root, r.URL.Query().Get("path"))
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	f, fi, err := openRegularInRoot(root, path)
	if err != nil {
		http.NotFound(w, r)
		return
	}
	defer f.Close()
	if fi.Size() > maxClaudeFileBytes {
		http.Error(w, "file is too large to preview", http.StatusRequestEntityTooLarge)
		return
	}
	data, err := io.ReadAll(io.LimitReader(f, maxClaudeFileBytes+1))
	if err != nil {
		http.Error(w, "could not read task file", http.StatusInternalServerError)
		return
	}
	response := claudeFileResponse{
		Path:       rel,
		Name:       filepath.Base(rel),
		Size:       fi.Size(),
		ModifiedAt: fi.ModTime().UTC().Format(time.RFC3339),
	}
	if bytes.IndexByte(data, 0) >= 0 {
		response.Binary = true
		response.Unavailable = "二进制文件不在浏览器中展开。"
	} else {
		response.Content = string(data)
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	_ = json.NewEncoder(w).Encode(response)
}
