"""OpenHarmony source-role classification and bounded build metadata parsing.

The classifier is deliberately path-oriented and conservative.  It does not
execute GN, import repository code, or infer ownership from a filename that is
not a known OpenHarmony convention.  C/C++ scanners can therefore use it as a
safe scope layer while keeping their language-specific extraction unchanged.
"""

from __future__ import annotations

import json
import re
from pathlib import Path, PurePosixPath
from typing import Any, Iterable


ROLE_NAMES = (
    "build_metadata",
    "fuzz",
    "generated",
    "interface_metadata",
    "production",
    "test",
    "third_party",
    "unknown",
    "unsupported_source",
)

SOURCE_SCOPES = ("production", "security-tests", "all")

_C_SOURCE_EXTENSIONS = frozenset(
    {".c", ".h", ".cpp", ".hpp", ".cc", ".cxx", ".hxx", ".hh"}
)
_UNSUPPORTED_SOURCE_EXTENSIONS = frozenset(
    {
        ".arkts",
        ".cj",
        ".ets",
        ".go",
        ".java",
        ".js",
        ".php",
        ".py",
        ".rb",
        ".rs",
        ".swift",
        ".ts",
        ".tsx",
        ".zig",
    }
)
_BUILD_METADATA_NAMES = frozenset({"build.gn", "build.gni", "bundle.json"})
_INTERFACE_METADATA_EXTENSIONS = frozenset({".idl", ".hcs", ".hdc"})
_THIRD_PARTY_SEGMENTS = frozenset({"third_party", "thirdparty", "external", "vendor"})
_FUZZ_SEGMENTS = frozenset({"fuzz", "fuzztest", "fuzz_tests"})
_TEST_SEGMENTS = frozenset(
    {"test", "tests", "testdata", "unittest", "unit_test", "unittests"}
)
_GENERATED_SEGMENTS = frozenset({"gen", "generated", "autogen", "autogenerated"})
_TARGET_RE = re.compile(
    r"(?m)\b(?:group|executable|static_library|shared_library|source_set|"
    r"action|action_foreach|ohos_[A-Za-z0-9_]+)\s*\(\s*['\"]([^'\"]+)['\"]"
)
_SOURCES_RE = re.compile(r"(?ms)\bsources\s*=\s*\[([^\]]*)\]")
_QUOTED_RE = re.compile(r"['\"]([^'\"]+)['\"]")
_MAX_METADATA_BYTES = 1024 * 1024


def _normalize_relative_path(relative_path: str | Path) -> str:
    """Return a portable relative path or reject traversal/absolute input."""
    raw = str(relative_path).replace("\\", "/")
    path = PurePosixPath(raw)
    if path.is_absolute() or ".." in path.parts:
        raise ValueError(f"relative path escapes repository: {relative_path}")
    parts = [part for part in path.parts if part not in ("", ".")]
    if not parts:
        raise ValueError("relative path must not be empty")
    return "/".join(parts)


def _unique(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value not in seen:
            seen.add(value)
            result.append(value)
    return result


class OpenHarmonyScopeClassifier:
    """Classify repository paths and parse small, static build manifests.

    ``source_scope`` controls which source roles are eligible for C/C++
    extraction.  Third-party code and metadata remain excluded in every scope;
    they are still counted so an omission cannot look like a clean scan.
    """

    _ACCEPTED_ROLES = {
        "production": frozenset({"production"}),
        "security-tests": frozenset({"production", "test", "fuzz", "generated"}),
        "all": frozenset({"production", "test", "fuzz", "generated", "unknown"}),
    }

    def __init__(self, repository_root: str | Path, *, source_scope: str = "production"):
        if source_scope not in SOURCE_SCOPES:
            choices = ", ".join(SOURCE_SCOPES)
            raise ValueError(f"source_scope must be one of: {choices}")
        self.repository_root = Path(repository_root).resolve()
        self.source_scope = source_scope

    def classify(self, relative_path: str | Path) -> str:
        """Return one stable role for a repository-relative path."""
        relative = _normalize_relative_path(relative_path)
        path = PurePosixPath(relative)
        lower_parts = tuple(part.lower() for part in path.parts)
        basename = lower_parts[-1]
        suffix = path.suffix.lower()

        if basename in _BUILD_METADATA_NAMES or suffix in {".gn", ".gni"}:
            return "build_metadata"
        if suffix in _INTERFACE_METADATA_EXTENSIONS:
            return "interface_metadata"
        if any(part in _THIRD_PARTY_SEGMENTS for part in lower_parts[:-1]):
            return "third_party"
        if any(part in _GENERATED_SEGMENTS for part in lower_parts[:-1]) or (
            "generated" in path.stem.lower() or path.stem.lower().endswith("_gen")
        ):
            return "generated"
        if any(part in _FUZZ_SEGMENTS for part in lower_parts[:-1]) or "fuzzer" in basename:
            return "fuzz"
        if any(part in _TEST_SEGMENTS for part in lower_parts[:-1]):
            return "test"
        if basename.startswith("test_") or path.stem.lower().endswith("_test"):
            return "test"
        if suffix in _C_SOURCE_EXTENSIONS:
            return "production"
        if suffix in _UNSUPPORTED_SOURCE_EXTENSIONS:
            return "unsupported_source"
        return "unknown"

    def accepts(self, role: str) -> bool:
        """Whether ``role`` is eligible under the configured source scope."""
        return role in self._ACCEPTED_ROLES[self.source_scope]

    def is_c_source(self, relative_path: str | Path) -> bool:
        """Return whether the path uses one of the C/C++ source extensions."""
        return PurePosixPath(_normalize_relative_path(relative_path)).suffix.lower() in _C_SOURCE_EXTENSIONS

    def collect_build_metadata(
        self,
        candidates: Iterable[tuple[Path, str]] | None = None,
    ) -> dict[str, Any]:
        """Read known metadata files without executing repository build code.

        ``candidates`` is supplied by the shared safe repository walker when
        available.  The standalone fallback rejects symlinks and paths that
        resolve outside the repository before reading a bounded number of bytes.
        """
        if candidates is None:
            candidates = self._find_metadata_candidates()

        bundle_manifests: list[dict[str, Any]] = []
        build_files: list[dict[str, Any]] = []
        parse_failures: list[dict[str, str]] = []
        for path, relative in sorted(candidates, key=lambda item: item[1]):
            name = PurePosixPath(relative).name.lower()
            try:
                text = self._read_bounded(path)
                if name == "bundle.json":
                    bundle_manifests.append(self._parse_bundle(relative, text))
                else:
                    build_files.append(self._parse_gn(relative, text))
            except (OSError, UnicodeError, ValueError) as exc:
                parse_failures.append({"path": relative, "reason": str(exc)})

        return {
            "bundle_manifests": bundle_manifests,
            "build_files": build_files,
            "parse_failures": parse_failures,
        }

    def _find_metadata_candidates(self) -> list[tuple[Path, str]]:
        root = self.repository_root
        if not root.is_dir():
            return []
        candidates: list[tuple[Path, str]] = []
        root_real = root.resolve()
        for path in root.rglob("*"):
            if path.is_symlink() or not path.is_file():
                continue
            try:
                path.resolve().relative_to(root_real)
            except ValueError:
                continue
            relative = path.relative_to(root).as_posix()
            if PurePosixPath(relative).name.lower() in _BUILD_METADATA_NAMES or path.suffix.lower() in {".gn", ".gni"}:
                candidates.append((path, relative))
        return candidates

    @staticmethod
    def _read_bounded(path: Path) -> str:
        size = path.stat().st_size
        if size > _MAX_METADATA_BYTES:
            raise ValueError(f"metadata file exceeds {_MAX_METADATA_BYTES} bytes")
        return path.read_text(encoding="utf-8")

    @staticmethod
    def _parse_bundle(relative: str, text: str) -> dict[str, Any]:
        payload = json.loads(text)
        if not isinstance(payload, dict):
            raise ValueError("bundle.json must contain a JSON object")

        component = ""
        for candidate in (
            payload.get("component"),
            payload.get("name"),
            payload.get("module", {}).get("name") if isinstance(payload.get("module"), dict) else None,
        ):
            if isinstance(candidate, dict):
                candidate = candidate.get("name")
            if isinstance(candidate, str) and candidate:
                component = candidate
                break

        targets: list[str] = []
        build = payload.get("build")
        if isinstance(build, dict):
            raw_targets = build.get("targets", [])
        else:
            raw_targets = build if isinstance(build, list) else []
        if isinstance(raw_targets, list):
            targets = [item for item in raw_targets if isinstance(item, str) and item]
        return {"path": relative, "component": component, "targets": _unique(targets)}

    @staticmethod
    def _parse_gn(relative: str, text: str) -> dict[str, Any]:
        targets = _unique(match.group(1) for match in _TARGET_RE.finditer(text))
        sources: list[str] = []
        for block in _SOURCES_RE.findall(text):
            sources.extend(value for value in _QUOTED_RE.findall(block) if value)
        return {
            "path": relative,
            "targets": targets,
            "sources": _unique(sources),
        }
