"""Explainable path classification and ranking for OpenGrok candidates.

OpenGrok full-text searches often return a mixture of production source,
generated build output, test resources, SELinux policy, kernel artifacts and
logs.  This module ranks those paths without deleting any candidate.  The
weights are intentionally visible in the returned feature list so a later Web
view can explain why a path moved up or down.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import PurePosixPath
import re
from typing import Any, Iterable

from .target_normalizer import TargetSpec


class PathClassificationError(ValueError):
    """Raised when a candidate path is not a safe repository-relative path."""


_SOURCE_EXTENSIONS = frozenset({".c", ".h", ".cc", ".cpp", ".cxx", ".hh", ".hpp", ".hxx"})
_MAX_PATH_LENGTH = 2048
_TEST_SEGMENTS = frozenset({"test", "tests", "testdata", "unittest", "unit_test", "unittests"})
_FUZZ_SEGMENTS = frozenset({"fuzz", "fuzztest", "fuzz_tests", "fuzzing"})
_GENERATED_SEGMENTS = frozenset({"gen", "generated", "autogen", "autogenerated", "out", "obj", "dist"})
_THIRD_PARTY_SEGMENTS = frozenset({"third_party", "thirdparty", "external", "vendor"})
_SERVICE_SEGMENTS = frozenset({"service", "services", "server", "daemon", "init", "domain"})
_BUILD_NAMES = frozenset({"build.gn", "build.gni", "bundle.json", "args.gn"})
_LOG_NAMES = frozenset({"last_kmsg", "logcat", "trace", "traces"})
_LOG_SEGMENTS = frozenset({"log", "logs", "trace", "traces", "logging"})
_KERNEL_SEGMENTS = frozenset({"kernel", "linux-headers", "kernel_headers"})
_SELINUX_SEGMENTS = frozenset({"selinux", "sepolicy", "policy"})
_PATH_COMPONENT_RE = re.compile(r"[A-Za-z0-9]+")


def _normalize_path(path: str) -> str:
    if not isinstance(path, str) or not path.strip():
        raise PathClassificationError("候选路径必须是非空字符串")
    value = path.strip()
    if len(value) > _MAX_PATH_LENGTH:
        raise PathClassificationError(f"候选路径过长（上限 {_MAX_PATH_LENGTH} 个字符）")
    if any(ord(char) < 0x20 or ord(char) == 0x7F for char in value):
        raise PathClassificationError("候选路径包含控制字符")
    if "\x00" in value or "?" in value or "#" in value or "\\" in value:
        raise PathClassificationError("候选路径包含禁止字符")
    if "://" in value:
        raise PathClassificationError("候选路径不能是 URL")
    parts = [part for part in value.split("/") if part]
    if not parts or any(part in {".", ".."} for part in parts):
        raise PathClassificationError("候选路径包含路径穿越片段")
    return "/" + "/".join(parts)


def _compact(value: str) -> str:
    return "".join(char.lower() for char in value if char.isalnum())


def _target_terms(target: TargetSpec | None) -> tuple[str, ...]:
    if target is None:
        return ()
    values = [target.basename, target.service_hint, target.macro_hint]
    terms: list[str] = []
    for value in values:
        if not value:
            continue
        compact = _compact(value)
        if compact and compact not in terms:
            terms.append(compact)
        for piece in _PATH_COMPONENT_RE.findall(value):
            compact_piece = _compact(piece)
            if len(compact_piece) >= 3 and compact_piece not in terms:
                terms.append(compact_piece)
    return tuple(terms)


@dataclass(frozen=True)
class PathFeature:
    """One transparent score contribution."""

    code: str
    label: str
    weight: int

    def to_dict(self) -> dict[str, Any]:
        return {"code": self.code, "label": self.label, "weight": self.weight}


@dataclass(frozen=True)
class PathClassification:
    """Classification and explainable score for one candidate path."""

    path: str
    role: str
    score: int
    features: tuple[PathFeature, ...]
    source_extension: str

    @property
    def is_production(self) -> bool:
        return self.role == "production"

    def to_dict(self) -> dict[str, Any]:
        return {
            "path": self.path,
            "role": self.role,
            "score": self.score,
            "source_extension": self.source_extension,
            "features": [feature.to_dict() for feature in self.features],
        }


def classify_path(path: str, *, target: TargetSpec | None = None) -> PathClassification:
    """Classify one path and calculate a score without dropping it."""

    normalized = _normalize_path(path)
    pure = PurePosixPath(normalized)
    components = tuple(part.lower() for part in pure.parts)
    basename = pure.name.lower()
    stem = pure.stem.lower()
    extension = pure.suffix.lower()
    features: list[PathFeature] = []

    def add(code: str, label: str, weight: int) -> None:
        features.append(PathFeature(code, label, weight))

    is_third_party = any(part in _THIRD_PARTY_SEGMENTS for part in components[:-1])
    is_test = any(part in _TEST_SEGMENTS for part in components[:-1]) or basename.startswith("test_") or stem.endswith("_test")
    is_fuzz = any(part in _FUZZ_SEGMENTS for part in components[:-1]) or "fuzzer" in basename
    is_generated = (
        any(part in _GENERATED_SEGMENTS for part in components[:-1])
        or "generated" in stem
        or stem.endswith("_gen")
        or basename.endswith((".z.so", ".so", ".a", ".o"))
    )
    is_build = basename in _BUILD_NAMES or extension in {".gn", ".gni"}
    is_selinux = (
        any(part in _SELINUX_SEGMENTS for part in components[:-1])
        or extension == ".te"
        or basename in {"file_contexts", "file_contexts_tmp", "system.conf"}
    )
    is_kernel = any(part in _KERNEL_SEGMENTS for part in components[:-1]) or basename.endswith((".ko", ".dts", ".dtsi"))
    is_log = any(part in _LOG_SEGMENTS for part in components[:-1]) or basename in _LOG_NAMES or extension in {".log", ".trace"}
    is_source = extension in _SOURCE_EXTENSIONS

    if is_third_party:
        role = "third_party"
        add("third_party", "第三方/外部目录，降低优先级", -55)
    elif is_fuzz:
        role = "fuzz"
        add("fuzz", "模糊测试目录或 fuzzer 文件，降低优先级但保留", -48)
    elif is_test:
        role = "test"
        add("test", "测试目录或测试文件，降低优先级但保留", -45)
    elif is_build:
        role = "build"
        add("build", "构建元数据文件，降低源码候选优先级", -38)
    elif is_generated:
        role = "generated"
        add("generated", "生成物/构建输出目录，降低优先级但保留", -40)
    elif is_selinux:
        role = "selinux"
        add("selinux", "SELinux/策略或上下文文件，降低优先级但保留", -34)
    elif is_kernel:
        role = "kernel"
        add("kernel", "内核或内核产物路径，降低优先级但保留", -30)
    elif is_log:
        role = "log"
        add("log", "日志/跟踪资源，降低优先级但保留", -32)
    elif is_source:
        role = "production"
        add("source", "C/C++ 源码或头文件", 42)
    else:
        role = "unknown"
        add("unknown", "未识别的文件类型，保持候选但降低优先级", -20)

    if is_source and role == "production":
        if extension in {".h", ".hh", ".hpp", ".hxx"}:
            add("header", "生产头文件可能包含宏、常量或接口定义", 10)
        else:
            add("implementation", "生产实现文件", 8)

    service_matches = [part for part in components[:-1] if part in _SERVICE_SEGMENTS]
    if service_matches:
        add("service_context", "路径包含服务/初始化上下文：" + "/".join(service_matches), 12)
    if any(part in {"src", "source", "include", "interfaces", "innerkits"} for part in components[:-1]):
        add("source_context", "路径位于源码、头文件或接口目录", 5)

    terms = _target_terms(target)
    if terms:
        compact_path = _compact(normalized)
        compact_stem = _compact(stem)
        exact_terms = [term for term in terms if term and term in compact_stem]
        path_terms = [term for term in terms if term and term in compact_path]
        if exact_terms:
            add("target_basename", "文件名与目标标识匹配：" + ",".join(exact_terms), 38)
        elif path_terms:
            add("target_path", "路径包含目标标识：" + ",".join(path_terms), 20)
        # A shared service prefix (e.g. param in paramservice/param_utils)
        # is weaker evidence than an exact match but remains useful for macro
        # headers and sibling implementation files.
        prefixes = [term[:5] for term in terms if len(term) >= 5 and term[:5] in compact_stem]
        if prefixes and not exact_terms:
            add("target_prefix", "文件名包含目标标识前缀：" + ",".join(prefixes), 12)

    score = sum(feature.weight for feature in features)
    return PathClassification(
        path=normalized,
        role=role,
        score=score,
        features=tuple(features),
        source_extension=extension,
    )


def rank_paths(paths: Iterable[str], *, target: TargetSpec | None = None) -> tuple[PathClassification, ...]:
    """Classify and stably rank unique candidate paths.

    Deduplication here only removes repeated representations of the same path;
    no role is filtered out.  The original path remains in every result's
    ``PathClassification`` for UI display and audit.
    """

    if isinstance(paths, (str, bytes)):
        raise PathClassificationError("paths 必须是路径序列，而不是单个字符串")
    unique: dict[str, PathClassification] = {}
    try:
        values = list(paths)
    except TypeError as exc:
        raise PathClassificationError("paths 必须是可迭代对象") from exc
    if not values:
        return ()
    for path in values:
        classification = classify_path(path, target=target)
        unique.setdefault(classification.path, classification)
    return tuple(sorted(unique.values(), key=lambda item: (-item.score, item.path)))
